[Finishes #187355051] user can register and verify his/her account
atlp-rwanda/e-commerce-ones-and-zeroes-fn pull request #11
Opened 2024-06-16 17:23 UTC by Celestin4

2024-06-21 08:40 UTC, shema-surge approved these changes

2024-06-21 08:52 UTC, Christian-Ishimwe approved these changes

2024-06-21 09:09 UTC, igorihimbazwe approved these changes

2024-06-21 17:16 UTC, UmuhireJessie requested changes
Good work @Celestin4, Please:
1. Consider adding a way to view/hide the password
<img width="1512" alt="Screenshot 2024-06-21 at 19 05 19" src="https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-fn/assets/86103578/e3564288-c0e4-48df-afc3-c8df03129d0c">

2. The color of the close icon on the toast is not visible once hovered on, you may consider changing it to something visible.
<img width="1512" alt="Screenshot 2024-06-21 at 19 07 35" src="https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-fn/assets/86103578/c3fc3fdd-4335-46ca-91b2-dd0f33633efe">

2024-06-26 06:52 UTC, UmuhireJessie approved these changes

2024-06-26 06:52 UTC, merged