[Delivers #187355052] Users should be presented with a reset password…
atlp-rwanda/e-commerce-ones-and-zeroes-fn pull request #14
Opened 2024-06-21 08:37 UTC by Christian-Ishimwe

… link

2024-06-21 08:41 UTC, shema-surge approved these changes

2024-06-21 20:32 UTC, Celestin4 approved these changes

2024-06-22 20:36 UTC, UmuhireJessie requested changes
The reset route is broken
<img width="1512" alt="Screenshot 2024-06-22 at 22 34 49" src="https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-fn/assets/86103578/7e505be6-bc59-4bf9-aab3-9eaa23783ca8">

2024-07-02 07:06 UTC, UmuhireJessie commented on .DS_Store
Remove this file and add it in `.gitignore` file

2024-07-02 07:07 UTC, UmuhireJessie commented on __tests__/.DS_Store
Remove this file and add it in `.gitignore`

2024-07-02 07:09 UTC, UmuhireJessie commented on src/views/Login.tsx
> +    <Link to={'/reset'}>Forgot password?</Link>
Is there a perfect way to show this instead of having it as a link? You can think of italics, hovering effect,...

2024-07-02 07:18 UTC, UmuhireJessie requested changes
Good work @Christian-Ishimwe , please note:
1. Can you add all the environment variables for the testing purpose
<img width="1512" alt="Screenshot 2024-07-02 at 09 04 33" src="https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-fn/assets/86103578/78e1544c-9023-4077-a9ef-5d1a62bece64">

2. Can you improve the design of this link 
<img width="1512" alt="Screenshot 2024-07-02 at 09 05 54" src="https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-fn/assets/86103578/b765c5d8-97af-43cc-a513-43cb0fdab12f">

2024-07-03 13:27 UTC, pacifiquemboni approved these changes

2024-07-03 15:08 UTC, lilika67 approved these changes

2024-07-03 16:22 UTC, UmuhireJessie approved these changes

2024-07-03 16:23 UTC, merged