Ft-user should login using email and  password
atlp-rwanda/e-commerce-ones-and-zeroes-fn pull request #15
Opened 2024-06-21 14:49 UTC by Celestin4

2024-06-24 16:41 UTC, UmuhireJessie requested changes
Good work @Celestin4 but please consider the following:
1. Add a hide/show password option
<img width="1512" alt="Screenshot 2024-06-24 at 18 39 16" src="https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-fn/assets/86103578/37702bc6-a17f-4d16-8fa7-94c9debefa71">

2. Add a valid backend link so that we can test your feature
<img width="1512" alt="Screenshot 2024-06-24 at 18 38 33" src="https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-fn/assets/86103578/7c58e5ad-bffc-4835-bc68-304082f89482">

2024-06-26 06:59 UTC, UmuhireJessie requested changes
@Celestin4, I can not test your PR, please check your backend URL:
<img width="1512" alt="Screenshot 2024-06-26 at 08 54 05" src="https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-fn/assets/86103578/18675f0a-a7a6-42e3-8657-b2d54cea07c1">

2024-06-26 08:10 UTC, lilika67 approved these changes

2024-06-26 15:21 UTC, Christian-Ishimwe approved these changes

2024-06-26 15:32 UTC, shema-surge approved these changes

2024-06-26 15:37 UTC, pacifiquemboni approved these changes

2024-06-26 16:29 UTC, UmuhireJessie commented
Can you please add deployment for your branch?

2024-06-26 16:34 UTC, UmuhireJessie commented on src/redux/slices/loginSlice.ts
> +            localStorage.setItem('token', response.data.token);
It is advisable to hash the token so everyone in production can't see it. But this is okay for now

2024-06-26 16:34 UTC, UmuhireJessie approved these changes

2024-06-26 16:37 UTC, UmuhireJessie commented
It is advisable to hash a JWT on the front end is advisable so that just everyone does not see it. Also, please change your commit message

2024-06-26 19:27 UTC, merged