[Delivered #187355059]Users should be able to view and edit their pro…
atlp-rwanda/e-commerce-ones-and-zeroes-fn pull request #18
Opened 2024-06-24 13:53 UTC by pacifiquemboni

## 1.What does this PR do?
Users should be able to view and edit their profiles

## 2.Description
I want to get my profile created once I register for the application.
I want my profile to display my:
 ### 1.Personal Information
   -name, email,gender, birthdate,
   -preferred language, preferred currency,where you live,
 ### 2.Billing Address (check the right fields of the billing address)
![Screenshot 2024-06-24 114255](https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-fn/assets/57124925/ffb512fc-8c77-481f-9608-5fa6a5c2fe5b)
![Screenshot 2024-06-24 114309](https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-fn/assets/57124925/5c091a61-b502-447e-bf3b-cd912052e5f2)
![Screenshot 2024-06-24 114343](https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-fn/assets/57124925/fef6fb93-cbab-47ba-b233-8e4ff4a81b19)
![Screenshot 2024-06-24 114408](https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-fn/assets/57124925/14fda45d-9922-40c3-86d2-2c30959445ad)

## 3.Acceptance Criteria
I want to be able to Edit my profile, but I should NOT be able to edit another users profile
### Scenario:
Given User registers to be a member of the App.
Registration is done.
User Profile is created.

2024-06-24 16:23 UTC, UmuhireJessie commented on __tests__/userslice.test.tsx
Why are you having this file if every code in it is commented?

2024-06-24 16:24 UTC, UmuhireJessie commented on src/components/billingAddress/updatebillingaddress.tsx
> +// import updateaddressimg from "../../assets/images/address.png";
Try as much as possible to avoid unnecessary codes

2024-06-24 16:28 UTC, UmuhireJessie requested changes
@pacifiquemboni :
1. The code looks good but cannot be tested using the deployed link. 
2. Please provide a deployed backend link
<img width="1512" alt="Screenshot 2024-06-24 at 18 25 49" src="https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-fn/assets/86103578/c4b55312-f17e-4a4a-8b3f-bc0d9a7db483">

2024-07-03 16:58 UTC, UmuhireJessie requested changes
Good work @pacifiquemboni, please consider the following:
1. Remove the error after successful update of profile
<img width="1512" alt="Screenshot 2024-07-03 at 18 50 46" src="https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-fn/assets/86103578/c3f7bac6-87d3-4d05-9033-6655b1342038">

2. Close the editing modal after sending the request (From the above the modal is still open yet we have the response)

3. I think you can find a better way to show that there is no data. Maybe add some styles on the word and remember to use the same way throughout. 
(As you see from the above, the birthdate is empty yet you haven't used `.....No data` word)

2024-07-05 16:42 UTC, shema-surge approved these changes

2024-07-05 16:55 UTC, lilika67 approved these changes

2024-07-08 15:58 UTC, UmuhireJessie commented on src/components/personalInfo/personalInfo.tsx
> +  const { id } = useParams<{ id?: string }>();
Consider checking why this is still undefined even when the login has succeeded.

2024-07-08 16:00 UTC, UmuhireJessie requested changes
@pacifiquemboni please check this out. Why is the user becoming undefined?
<img width="1512" alt="Screenshot 2024-07-08 at 17 54 51" src="https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-fn/assets/86103578/70419b11-91c5-4655-bf2e-66c25c343eb1">

2024-07-12 09:46 UTC, Celestin4 approved these changes

2024-07-12 15:31 UTC, UmuhireJessie approved these changes

2024-07-12 15:32 UTC, merged