[Delivers #187774876] buyer can see available products
atlp-rwanda/e-commerce-ones-and-zeroes-fn pull request #20
Opened 2024-06-27 17:33 UTC by lilika67

**1.What does this PR do?**

This is the feature for enabling a user/buyer to view all products available

**2.Description**
As a buyer, I should be able to retrieve a list of all items on the available list of products
Such that a high-level inspection is viable.

**3.Acceptance Criteria**
When the request body fails any validation checks
Then:
- A json object containing an status property with the appropriate 4XX code, and an error property with the correct error message should be sent to the requesting client describing the validation error
-The item list should be paginated

**Screenshot**

![image](https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-fn/assets/125905987/6ce1e113-d25a-44cb-900d-afe95b448a5c)
![image](https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-fn/assets/125905987/9a43ecf9-a745-4853-b3ac-d2b65d841286)

**Relevant Pivotal tracker stories**

[Link](https://www.pivotaltracker.com/story/show/187774876)

2024-06-28 06:07 UTC, Celestin4 approved these changes

2024-07-01 08:50 UTC, Christian-Ishimwe approved these changes

2024-07-02 07:58 UTC, UmuhireJessie commented on src/assets/images/Andela-pic.jpg
They are some default images that you may adapt to rather than having actual images.
Here are some [examples](https://www.google.com/search?q=default+images&rlz=1C5CHFA_enRW1107RW1107&oq=default+images&gs_lcrp=EgZjaHJvbWUyCQgAEEUYORiABDIHCAEQABiABDIHCAIQABiABDIKCAMQABgKGBYYHjIMCAQQABgKGA8YFhgeMgoIBRAAGA8YFhgeMgoIBhAAGA8YFhgeMgoIBxAAGA8YFhgeMggICBAAGBYYHjIICAkQABgWGB7SAQkxMDM3MWowajeoAgCwAgA&sourceid=chrome&ie=UTF-8)

2024-07-02 08:04 UTC, UmuhireJessie commented on src/components/ExampleList.tsx
If you are not using the file (any file), remove it rather than commenting it.

2024-07-02 08:07 UTC, UmuhireJessie requested changes
Good work @lilika67. The implementation looks fine, but I can not see the products. Why are we getting the `401` error
<img width="1512" alt="Screenshot 2024-07-02 at 09 32 32" src="https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-fn/assets/86103578/6ce95f44-733a-4fa5-a1f0-c28b104aa616">

2024-07-03 16:32 UTC, UmuhireJessie requested changes
So far so good @lilika67, Please consider:
1. showing that there is a section of the Product and then showing that there is a problem or an error, instead of just showing the error, which is confusing. 
<img width="1512" alt="Screenshot 2024-07-03 at 18 28 47" src="https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-fn/assets/86103578/7f7c2921-a3c6-4435-ba9f-30119933aa37">

2. You may also think of a better representation (design) of how to show an error, i.e., improve the CSS. For instance, it can be inside a card,  or any other appealing way

2024-07-04 21:26 UTC, UmuhireJessie commented on src/components/AvailableProduct/productPage.tsx
> +  if (loading) return <div>Loading...</div>;
Can you render this `Loading ....` under the Product title? Otherwise, someone might need clarification about which data are being loaded.

2024-07-04 21:27 UTC, UmuhireJessie commented on src/components/AvailableProduct/productPage.tsx
> +          <h3>No available products in our stock</h3></div></div>
You might even consider rendering it here or above.

2024-07-04 23:06 UTC, UmuhireJessie requested changes
Check my comments. What are we loading?
<img width="1512" alt="Screenshot 2024-07-05 at 01 04 38" src="https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-fn/assets/86103578/b710b7a5-0d3f-4bef-850b-eca45ccf4f6c">

2024-07-05 10:34 UTC, UmuhireJessie approved these changes

2024-07-05 10:34 UTC, merged