User adding item in cart
atlp-rwanda/e-commerce-ones-and-zeroes-fn pull request #23
Opened 2024-07-06 09:27 UTC by pacifiquemboni

2024-07-08 06:58 UTC, UmuhireJessie commented
Can you make products available for testing purposes?
<img width="1512" alt="Screenshot 2024-07-08 at 08 57 51" src="https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-fn/assets/86103578/ff74db0a-5ca0-4c93-9eca-0a9e9e4d5fa8">

2024-07-09 09:08 UTC, lilika67 approved these changes

2024-07-12 15:30 UTC, UmuhireJessie approved these changes

2024-07-12 21:34 UTC, UmuhireJessie commented on src/components/cart/cart.tsx
> +        <div>Loading...</div>
Can you improve the design on the loading sign?

2024-07-12 21:35 UTC, UmuhireJessie requested changes
Check comments and please resolve the conflicts

2024-07-16 08:08 UTC, Celse13 commented
I have one more question, which is all about verifying if the preferred currency in the profile settings correlates with the currency being displayed on the cart

2024-07-16 08:10 UTC, Celse13 commented
I have one more question which is about verifying if the currency in the profile settings correlates with the currency being displayed on the cart.

2024-07-16 19:51 UTC, UmuhireJessie commented on .env.example
> +>>>>>>> a9b4a07 ([Delivers #187355068] user adding item in cart)
Remove these lines

2024-07-16 19:56 UTC, UmuhireJessie requested changes
Check my comments

2024-07-17 20:50 UTC, igorihimbazwe approved these changes

2024-07-18 08:58 UTC, shema-surge approved these changes

2024-07-18 17:25 UTC, UmuhireJessie approved these changes

2024-07-18 17:25 UTC, merged