[Finishes #187355076] Product recommendation
atlp-rwanda/e-commerce-ones-and-zeroes-fn pull request #26
Opened 2024-07-11 16:54 UTC by Christian-Ishimwe

### What does this PR do?
Product recommandation

### Description of task to be completed
As a user navigate to view one product, he will be recommendated the product he might like.
The products are brought from the backend, with the algorithm defined on the backend.

3. How should this be manually tested?
this PR can be tested through navigating to the url provided by netlift PR preview: [https://deploy-preview-26--dponesandzereos.netlify.app/](url) 
Then, for the available products, you can view more on a certain product.
<img width="1426" alt="Screenshot 2024-07-11 at 20 49 04" src="https://github.com/user-attachments/assets/2b1fed64-e3e5-4574-97df-3f001dd34092">
<img width="1399" alt="Screenshot 2024-07-11 at 20 49 19" src="https://github.com/user-attachments/assets/eb24c51c-10ec-4fc5-afa6-fc692685ff2a">

2024-07-12 08:57 UTC, Celse13 approved these changes

2024-07-12 09:15 UTC, lilika67 approved these changes

2024-07-12 09:45 UTC, Celestin4 approved these changes

2024-07-12 21:18 UTC, UmuhireJessie requested changes
Could you consider changing the way you this error and allow all users to see recommended products? You may prefer to add some products if the user is logged in.
<img width="1512" alt="Screenshot 2024-07-12 at 23 06 10" src="https://github.com/user-attachments/assets/04323733-5e78-42fe-b834-5f841fc3afae">

2024-07-17 17:52 UTC, UmuhireJessie approved these changes

2024-07-17 17:52 UTC, merged