[Finishes #187355053] two factor authentication for the seller
atlp-rwanda/e-commerce-ones-and-zeroes-fn pull request #28
Opened 2024-07-21 19:20 UTC by Christian-Ishimwe

2024-07-21 20:02 UTC, pacifiquemboni commented
Good work christian, remember to add how we are going to test this PR in description

2024-07-21 21:31 UTC, Celestin4 approved these changes

2024-07-21 21:40 UTC, Celse13 approved these changes

2024-07-21 22:13 UTC, venuste-20002 approved these changes

2024-07-22 13:43 UTC, UmuhireJessie commented on src/redux/slices/loginSlice.ts
> +
remove these if they are of no use

2024-07-22 13:45 UTC, UmuhireJessie approved these changes

2024-07-22 13:46 UTC, UmuhireJessie requested changes
Check my comments

2024-07-22 14:08 UTC, UmuhireJessie approved these changes

2024-07-22 14:09 UTC, merged