[Finishes #187355055 #187355057 #187848506] seller-page
atlp-rwanda/e-commerce-ones-and-zeroes-fn pull request #30
Opened 2024-07-22 04:06 UTC by venuste-20002

1: what does this PR do?

 one this  PR A seller should be able to view a single item and have a different view of all Items in seller's collection,
 A seller should be able to update an product item from their collection  and 
 A seller should be able to delete a specific item from their collection

2: Relevant Stories:

### https://www.pivotaltracker.com/story/show/187355055
### https://www.pivotaltracker.com/story/show/187355057
### https://www.pivotaltracker.com/story/show/187848506

3: Screenshots
### ![Screenshot 2024-07-22 053351](https://github.com/user-attachments/assets/c04ceaa8-318f-41ab-b0d3-ebb1c9754e92)

###  ![Screenshot 2024-07-22 053425](https://github.com/user-attachments/assets/84eb169e-3ded-4f66-ad57-15619df9c881)

### ![Screenshot 2024-07-22 053737](https://github.com/user-attachments/assets/9036acda-db42-4d62-8f1f-20b6cf02fc1f)

### ![Screenshot 2024-07-22 053457](https://github.com/user-attachments/assets/904e60ec-b626-46ab-a163-a10390e878f7)

### ![Screenshot 2024-07-22 053603](https://github.com/user-attachments/assets/4aeb48f0-01bf-4702-980e-c113912eeb46)

2024-07-22 06:29 UTC, UmuhireJessie commented on src/Pages/sellerSingleProduct/sellerSingleProduct.tsx
> +    if (window.confirm("Are you sure you want to delete this image?")) {
Can you please use a modal instead of an alert

2024-07-22 06:31 UTC, UmuhireJessie commented on src/asios.tsx
> +
Remove these comments.

2024-07-22 06:33 UTC, UmuhireJessie commented on src/redux/store.ts
> +>>>>>>> b05dd2c ([Finishes #187355055 #187355057 #187848506] seller-page)
Please ensure that you have resolved conflicts well

2024-07-22 06:34 UTC, UmuhireJessie commented on src/redux/store.ts
> +>>>>>>> b05dd2c ([Finishes #187355055 #187355057 #187848506] seller-page)
Please resolve conflicts satisfactorily.

2024-07-22 06:36 UTC, UmuhireJessie requested changes
Please check my comments

2024-07-22 13:22 UTC, Celestin4 approved these changes

2024-07-22 14:09 UTC, Christian-Ishimwe approved these changes

2024-07-22 14:11 UTC, Christian-Ishimwe approved these changes
Can you work on resolving the conflicts?

2024-07-22 18:10 UTC, UmuhireJessie requested changes
@venuste-20002 please work on:
1. Updating the page after login without refresh. The page is just blank
<img width="1512" alt="Screenshot 2024-07-22 at 20 04 13" src="https://github.com/user-attachments/assets/c20c9138-d23a-444e-ba07-f56e0a54f75a">

2. Consider improving the design of this search box and the side bar. Consult Shema's work as a reference on the width of side bar
<img width="1512" alt="Screenshot 2024-07-22 at 20 08 04" src="https://github.com/user-attachments/assets/0a378dbd-d490-4921-af12-08177c01b1d3">

2024-07-24 12:36 UTC, lilika67 approved these changes

2024-07-26 09:18 UTC, closed without merging