[Finishes #187355064] Users should be able to chat
atlp-rwanda/e-commerce-ones-and-zeroes-fn pull request #31
Opened 2024-07-24 10:32 UTC by lilika67

**What Does This PR DO?**
 
This is the feature that will allow users to chat.
It uses WebSocket to allow bidirectional communication between users who are currently online. 

**Why is this important?**

Having travellers interacting with each other on the platform adds value to it as it allows them to asks questions about places, offer recommendations, guidance 

**Acceptance Criteria**

**GIVEN** the user is online
**WHEN** they open the chat tab
**THEN** they should be able to read all of the past chats

**GIVEN** the user is online
**WHEN** they open the chat tab
**THEN** they should be able to post a public chat

**GIVEN**the user
**WHEN** they post a chat
**THEN** it should be able to be echoed to all online users in real time.

**ScreenShoot**

![image](https://github.com/user-attachments/assets/ae9429e6-989d-4375-b3b6-a7c7da1a3671)

2024-07-24 15:02 UTC, UmuhireJessie requested changes
@lilika67 
1. Please consider moving the closing icon in the chat modal 
<img width="1512" alt="Screenshot 2024-07-24 at 16 55 29" src="https://github.com/user-attachments/assets/6724fb9a-c1bb-4370-b8a5-63da886f6e2e">

2. Chat are not going through
<img width="1512" alt="Screenshot 2024-07-24 at 17 00 24" src="https://github.com/user-attachments/assets/721537bc-694e-4f6d-89c0-789d99759901">

3. From the above, please create the chat so that it is overlay over the product lists instead of spacing it out

2024-07-26 11:40 UTC, shema-surge approved these changes

2024-07-26 12:14 UTC, UmuhireJessie approved these changes

2024-07-26 12:18 UTC, pacifiquemboni approved these changes

2024-07-26 13:01 UTC, merged