[Finishes #187355043]Setup-SASS-processing
atlp-rwanda/e-commerce-ones-and-zeroes-fn pull request #5
Opened 2024-06-09 20:30 UTC by venuste-20002

#### What does this PR do?

 Install and setup SASS processing

#### Description of Task to be completed?

Objective:
Enable SASS pre-processing in the application to allow the use of both .scss and .css files for client-side styling.

Task Details:
1.Install SASS: Add the necessary dependencies for SASS to the project. This can be achieved using package managers such as npm
2.Configure SASS Pre-processing: create  the configuration files (e.g., webpack.config.js) to include SASS loaders

3.Verify Integration :Create a sample .scss file and import it into a React component to verify that the styles are applied correctly.

#### How should this be manually tested?
Step1> Clone The project
Step2> Switch to branch ch-SASS-processing
Step3> Install all packages by npm i
Step4> Run the project by npm start
Step 5> When the project is running, then  open the link http://localhost:9000

#### What are the relevant pivotal tracker/Trello stories?

https://www.pivotaltracker.com/story/show/187355043

#### Screenshots (if appropriate)

![Screenshot 2024-06-09 222647](https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-fn/assets/156195811/2c8da476-39b0-485a-b39b-fc3749fe8cea)

2024-06-10 13:49 UTC, igorihimbazwe requested changes
Remove Coverage Folder

2024-06-10 16:28 UTC, igorihimbazwe approved these changes

2024-06-10 16:34 UTC, lilika67 approved these changes

2024-06-10 23:01 UTC, UmuhireJessie commented on dist/bundle.js
Remove this folder

2024-06-10 23:02 UTC, UmuhireJessie requested changes
Work the comment

2024-06-11 18:19 UTC, UmuhireJessie approved these changes

2024-06-11 18:27 UTC, merged